// src/types/song.types.ts
import { Song } from './index';

// Type for creating a new song - omits song_id, created_at, and updated_at which are generated by the server
export interface SongCreate {
    artist_id: string;
    platform_id: number;
    platform_specific_id: string;
    title: string;
    artist_name_on_platform: string;
    album_name: string;
    url: string;
    cover_image_url: string;
    duration_ms: number;
    is_visible: boolean;
    genre?: string;
    preview_url?: string;
}

// Type for updating an existing song - requires song_id but all other fields are optional
export interface SongUpdate {
    song_id: string;
    artist_id?: string;
    platform_id?: number;
    platform_specific_id?: string;
    title?: string;
    artist_name_on_platform?: string;
    album_name?: string;
    url?: string;
    cover_image_url?: string;
    duration_ms?: number;
    is_visible?: boolean;
    genre?: string;
    preview_url?: string;
}

// Type for filtering songs
export interface SongFilter {
    title?: string;
    artist_id?: string;
    genre?: string;
    platform_id?: number;
    is_visible?: boolean;
}

// Type for song with additional platform information
export interface SongWithPlatform extends Song {
    platform?: {
        name: string;
        logo_url?: string;
    };
}
